-- Ad placements: size, position and targeting chosen by an admin.
ALTER TABLE "AdPlacement" ADD COLUMN IF NOT EXISTS "size" TEXT NOT NULL DEFAULT 'BANNER';
ALTER TABLE "AdPlacement" ADD COLUMN IF NOT EXISTS "width" INTEGER NOT NULL DEFAULT 1400;
ALTER TABLE "AdPlacement" ADD COLUMN IF NOT EXISTS "height" INTEGER NOT NULL DEFAULT 400;
ALTER TABLE "AdPlacement" ADD COLUMN IF NOT EXISTS "align" TEXT NOT NULL DEFAULT 'CENTER';
ALTER TABLE "AdPlacement" ADD COLUMN IF NOT EXISTS "textPosition" TEXT NOT NULL DEFAULT 'BOTTOM_LEFT';
ALTER TABLE "AdPlacement" ADD COLUMN IF NOT EXISTS "imageFit" TEXT NOT NULL DEFAULT 'COVER';
ALTER TABLE "AdPlacement" ADD COLUMN IF NOT EXISTS "device" TEXT NOT NULL DEFAULT 'ALL';
ALTER TABLE "AdPlacement" ADD COLUMN IF NOT EXISTS "listPosition" INTEGER NOT NULL DEFAULT 4;
ALTER TABLE "AdPlacement" ADD COLUMN IF NOT EXISTS "targetCity" TEXT NOT NULL DEFAULT '';
